### ISSUE TITLE
[FEATURE] Java process names are too simple

### ISSUE THREAD

**Issue by melin** [apache/celeborn#3031]
Execute jps. Displays celeborn java process name: master or worker, the name is too simple. Inconvenient identification

**Comment by turboFei** [comment]
Hi @melin
It is because the simple class of `org.apache.celeborn.service.deploy.master.Master` is `Master`.

You can use `jps -l` to show the full class name.

BTW, feel free to create ticket in celeborn jira for feature or bug fix requirement, https://issues.apache.org/jira/projects/CELEBORN/issues

Thanks for the question, I am closing it.
